set_property SRC_FILE_INFO {cfile:C:/Users/marku/Documents/EE2026/Lab/lab3/lab3.srcs/constrs_1/new/basys3_constraints.xdc rfile:../../../lab3.srcs/constrs_1/new/basys3_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports CLOCK]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {switch}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {LED}]
